### ISSUE TITLE
Legacy Swift Language Version issue

### ISSUE THREAD

**Issue by tofutim** [robin/TitlebarAndToolbar#4]
I cloned and on first run got this error:

![image](https://user-images.githubusercontent.com/157766/30733231-fb06ac44-9f2a-11e7-9c09-4e23139fddf4.png)

That said, I've never compiled a Swift project so perhaps I'm just missing something in my setup.

**Comment by tofutim** [comment]
I think I'm missing Swift 4.

**Comment by tofutim** [comment]
Looks like I have to update to Xcode 9. But I'm scared... reviews are not too favorable. How do you like it so far?

**Comment by robin** [comment]
You can check out a version before the migration.
